adminUser:
  password: vault:warriorclever/adminUser:password
  username: admin
dashboardUrl: https://dashboard.play-jxaas.live
enableDocker: false
pipelineUser:
  email: arcalos-admin@googlegroups.com
  token: vault:warriorclever/pipelineUser:token
  username: cloudbees-ci-cd-play[bot]
prow:
  hmacToken: vault:warriorclever/prow:hmacToken
segmentWriteKey: vault:warriorclever:segmentWriteKey
